#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <sstream>
#include <random>
#include <tuple>

using namespace std;

class SampleValidator {
public:
    static void validate(const string& file_path) {
        string path = file_path;
        if (path.length() < 4 || path.substr(path.length() - 4) != ".obj") {
            path += ".obj";
        }
        
        ifstream file(path);
        if (!file.is_open()) {
            cout << "[error] Failed to open file: " << path << endl;
            return;
        }
        
        string line;
        unsigned int count = 0;
        vector<tuple<float, float, float>> file_vertices;
        string current_name;
        
        cout << "Validating file: " << path << endl;

        while(getline(file, line)){
            if(line.empty() || line[0] == '#') continue;
            
            istringstream iss(line);
            string type;
            iss >> type;
            
            if (type == "v") {
                float x, y, z, w = 1.0;
                iss >> x >> y >> z;
                if (iss >> w) { } // successfully read w
                file_vertices.emplace_back(x, y, z); 
            } else if (type == "o" || type == "g") {
                iss >> current_name;
            } else if (type == "p") {
                vector<tuple<float, float, float>> points;
                string v_str;
                while (iss >> v_str) {
                    try {
                        size_t pos;
                        int v_idx = stoi(v_str, &pos);
                        if (v_idx < 0) v_idx = file_vertices.size() + v_idx + 1;
                        if (v_idx > 0 && v_idx <= file_vertices.size()) {
                            points.push_back(file_vertices[v_idx - 1]);
                        }
                    } catch (...) {}
                }
                if (!points.empty()) {
                    count++;
                }
            } else if (type == "l" || type == "f") {
                vector<tuple<float, float, float>> points;
                string v_str;
                while (iss >> v_str) {
                    try {
                        size_t pos;
                        int v_idx = stoi(v_str, &pos);
                        if (v_idx < 0) v_idx = file_vertices.size() + v_idx + 1;
                        if (v_idx > 0 && v_idx <= file_vertices.size()) {
                            points.push_back(file_vertices[v_idx - 1]);
                        }
                    } catch (...) {}
                }
                if (!points.empty()) {
                    if (type == "f" && points.front() != points.back()) {
                        points.push_back(points.front());
                    }
                    count++;
                }
            }
        }
        cout << "Validation successful. Found " << file_vertices.size() << " vertices and " << count << " objects." << endl;
    }
};

float getRandomFloat(float min_val, float max_val) {
    random_device rd;
    mt19937 gen(rd());
    uniform_real_distribution<float> dis(min_val, max_val);
    return dis(gen);
}

void interactiveGenerator() {
    string filename;
    cout << "Enter output filename (will append .obj if missing): ";
    cin >> filename;

    if (filename.length() < 4 || filename.substr(filename.length() - 4) != ".obj") {
        filename += ".obj";
    }

    float min_val = -100.0f;
    float max_val = 100.0f;
    char customRange;
    cout << "Use custom random range? (y/N): ";
    cin >> customRange;
    if (tolower(customRange) == 'y') {
        cout << "Enter min float value: ";
        cin >> min_val;
        cout << "Enter max float value: ";
        cin >> max_val;
    }

    int numPoints = 0, numLines = 0, numFaces = 0;
    cout << "Enter number of point objects to generate: ";
    cin >> numPoints;
    cout << "Enter number of line objects to generate (each with 2 vertices): ";
    cin >> numLines;
    cout << "Enter number of face/wireframe objects to generate (each with 3-6 vertices): ";
    cin >> numFaces;

    ofstream file(filename);
    if (!file.is_open()) {
        cout << "[error] Failed to open file for writing: " << filename << endl;
        return;
    }

    file << "# Generated by SampleGenerator\n";
    
    int vertex_count = 1;

    // Generate Points
    for (int i = 0; i < numPoints; ++i) {
        file << "o Point_" << i << "\n";
        file << "v " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << "\n";
        file << "p " << vertex_count << "\n";
        vertex_count++;
    }

    // Generate Lines
    for (int i = 0; i < numLines; ++i) {
        file << "o Line_" << i << "\n";
        file << "v " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << "\n";
        file << "v " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << "\n";
        file << "l " << vertex_count << " " << vertex_count + 1 << "\n";
        vertex_count += 2;
    }

    // Generate Faces
    random_device rd;
    mt19937 gen(rd());
    uniform_int_distribution<> polyDis(3, 6);

    for (int i = 0; i < numFaces; ++i) {
        file << "o Face_" << i << "\n";
        int polySize = polyDis(gen);
        for (int j = 0; j < polySize; j++) {
            file << "v " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << " " << getRandomFloat(min_val, max_val) << "\n";
        }
        file << "f";
        for (int j = 0; j < polySize; j++) {
            file << " " << vertex_count + j;
        }
        file << "\n";
        vertex_count += polySize;
    }

    file.close();
    cout << "Successfully wrote to " << filename << endl;

    // Auto validate
    cout << "\nRunning SampleValidator..." << endl;
    SampleValidator::validate(filename);
}

int main(int argc, char* argv[]) {
    if (argc > 1) {
        string cmd = argv[1];
        if (cmd == "validate" && argc > 2) {
            SampleValidator::validate(argv[2]);
            return 0;
        } else {
            cout << "Usage:\n";
            cout << "  " << argv[0] << "                   (Interactive generation)\n";
            cout << "  " << argv[0] << " validate <file.obj> (Validate existing obj file)\n";
            return 1;
        }
    }

    interactiveGenerator();
    return 0;
}